name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "*" ]
  workflow_dispatch:

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  VCPKG_BINARY_SOURCES: clear;nuget,GitHub,readwrite;nugettimeout,3600

permissions:
  contents: read
  packages: write

jobs:
  build:
    strategy:
      matrix:
        os: ['windows-2022', 'ubuntu-22.04']
        vcpkg_library_linkage: ['dynamic', 'static']
        include:
          - os: 'ubuntu-22.04'
            mono: 'mono'
          - os: 'windows-2022'
            mono: ''
          - os: 'ubuntu-22.04'
            vcpkg_library_linkage: 'static'
            vcpkg_target_triplet: 'x64-linux'
          - os: 'windows-2022'
            vcpkg_library_linkage: 'dynamic'
            vcpkg_target_triplet: 'x64-windows'
          - os: 'windows-2022'
            vcpkg_library_linkage: 'static'
            vcpkg_target_triplet: 'x64-windows-static'
        exclude:
          - os: 'ubuntu-22.04'
            vcpkg_library_linkage: 'dynamic'
  
    runs-on: ${{ matrix.os }}

    steps:
    - name: Install Ubuntu dependencies
      if: ${{ matrix.os == 'ubuntu-22.04' }}
      shell: bash
      run: sudo apt-get install autoconf-archive
    
    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
        submodules: 'recursive'

    - name: Bootstrap VCPKG
      shell: bash
      run: ./vcpkg/bootstrap-vcpkg.sh

    - name: Setup NuGet
      shell: bash
      run: |
        ${{matrix.mono}} $((./vcpkg/vcpkg fetch nuget) | tail -n 1) sources add \
            -source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" \
            -storepasswordincleartext \
            -name "GitHub" \
            -username "${{ github.repository_owner }}" \
            -password "${{ secrets.GITHUB_TOKEN }}"
        ${{matrix.mono}} $((./vcpkg/vcpkg fetch nuget) | tail -n 1) setapikey "${{ secrets.GITHUB_TOKEN }}" \
            -source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json"
        ${{matrix.mono}} $((./vcpkg/vcpkg fetch nuget) | tail -n 1) sources

    - name: Provision VCPKG
      shell: bash
      run: |
        cmake \
            -B "${{ github.workspace }}/build" \
            -DVCPKG_VERBOSE=ON \
            -DVCPKG_INSTALL_OPTIONS="--debug" \
            -DVCPKG_TARGET_TRIPLET="${{ matrix.vcpkg_target_triplet }}" \
            -DCMAKE_TOOLCHAIN_FILE="${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake" \
            "${{ github.workspace }}"
      
    - name: Upload Log Files
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: buildlogs
        path: |
          vcpkg/buildtrees/*/*.txt
          vcpkg/buildtrees/*/*.log
