name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "*" ]
  workflow_dispatch:

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  NUGET_REPOSITORY_ID: GitHubPackages
  VCPKG_BINARY_SOURCES: clear;nuget,GitHub,readwrite;nugettimeout,3600

jobs:
  build:
    runs-on: windows-2022

    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
        submodules: 'recursive'

    - name: Setup NuGet
      shell: pwsh
      run: |
        nuget sources add `
            -source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" `
            -storepasswordincleartext `
            -name "GitHub" `
            -username "${{ github.repository_owner }}" `
            -password "${{ secrets.GITHUB_TOKEN }}"
        nuget setapikey "${{ secrets.GITHUB_TOKEN }}" `
            -source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json"
        nuget sources

    - name: Provision VCPKG
      shell: pwsh
      run: |
        cmake `
            -B "${{ github.workspace }}/build" `
            -DVCPKG_VERBOSE=ON `
            -DVCPKG_INSTALL_OPTIONS="--debug" `
            -DCMAKE_TOOLCHAIN_FILE="${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake" `
            "${{ github.workspace }}"
      
    - name: Upload Log Files
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: buildlogs
        path: |
          vcpkg/buildtrees/*/*.txt
          vcpkg/buildtrees/*/*.log
